# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03d09db871fd06fe402f65972680815476a712fcb3fd3bd38a484774b7af8fdc6a3ce95c5ac198a081dfc13a028158b75db3313e4463a82bc85eb742adeb5c79

test:
  secret_key_base: 9cf07b3a9d21236a73726ef58942a61cc0ba4b23fed89e793fa47e09f0e962b1e99c33c26145e14ca764a8cf1edae28008fc63f88929c720d74a2b01713963e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
